-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 23:32:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL,
  `LastName` VARCHAR(50) NULL,
  `Email` VARCHAR(100) NULL,
  `Password` VARCHAR(100) NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `Address` VARCHAR(225) NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `AirportID` INT NOT NULL,
  `AirportName` VARCHAR(100) NULL,
  `City` VARCHAR(100) NULL,
  `Country` VARCHAR(100) NULL,
  `IATA_Code` VARCHAR(10) NULL,
  PRIMARY KEY (`AirportID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `AirlineID` INT NOT NULL,
  `AirlineName` VARCHAR(100) NULL,
  `IATA_Code` VARCHAR(10) NULL,
  `Country` VARCHAR(100) NULL,
  PRIMARY KEY (`AirlineID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `AircraftID` INT NOT NULL,
  `Model` VARCHAR(50) NULL,
  `Capacity` INT NULL,
  `Manufacturer` VARCHAR(50) NULL,
  `Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`AircraftID`, `Airline_AirlineID`),
  INDEX `fk_Aircraft_Airline1_idx` (`Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_Aircraft_Airline1`
    FOREIGN KEY (`Airline_AirlineID`)
    REFERENCES `mydb`.`Airline` (`AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `FlightID` INT NOT NULL,
  `FlightNumber` VARCHAR(10) NULL,
  `DepartureTime` DATETIME NULL,
  `ArrivalTime` DATETIME NULL,
  `Duration` VARCHAR(10) NULL,
  `DepartureAirportID` INT NULL,
  `ArrivalAirportID` INT NULL,
  `AircraftID` INT NULL,
  `AirlineID` INT NULL,
  `PilotID` INT NULL,
  `Airport_AirportID` INT NOT NULL,
  `Aircraft_AircraftID` INT NOT NULL,
  `Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`FlightID`, `Airport_AirportID`, `Aircraft_AircraftID`, `Airline_AirlineID`),
  INDEX `fk_Flight_Airport1_idx` (`Airport_AirportID` ASC) VISIBLE,
  INDEX `fk_Flight_Aircraft1_idx` (`Aircraft_AircraftID` ASC) VISIBLE,
  INDEX `fk_Flight_Airline1_idx` (`Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`Airport_AirportID`)
    REFERENCES `mydb`.`Airport` (`AirportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Aircraft1`
    FOREIGN KEY (`Aircraft_AircraftID`)
    REFERENCES `mydb`.`Aircraft` (`AircraftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_AirlineID`)
    REFERENCES `mydb`.`Airline` (`AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `PaymentID` INT NOT NULL,
  `Amount` DECIMAL(10,2) NULL,
  `PaymentDate` DATETIME NULL,
  `PaymentMethod` VARCHAR(20) NULL,
  PRIMARY KEY (`PaymentID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `BookingID` INT NOT NULL,
  `BookingDate` DATETIME NULL,
  `Status` VARCHAR(20) NULL,
  `UserID` INT NULL,
  `FlightID` INT NULL,
  `PaymentID` INT NULL,
  `User_UserID` INT NOT NULL,
  `Flight_FlightID` INT NOT NULL,
  `Payment_PaymentID` INT NOT NULL,
  PRIMARY KEY (`BookingID`, `User_UserID`, `Flight_FlightID`, `Payment_PaymentID`),
  INDEX `fk_Booking_User_idx` (`User_UserID` ASC) VISIBLE,
  INDEX `fk_Booking_Flight1_idx` (`Flight_FlightID` ASC) VISIBLE,
  INDEX `fk_Booking_Payment1_idx` (`Payment_PaymentID` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_User`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Flight1`
    FOREIGN KEY (`Flight_FlightID`)
    REFERENCES `mydb`.`Flight` (`FlightID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Payment1`
    FOREIGN KEY (`Payment_PaymentID`)
    REFERENCES `mydb`.`Payment` (`PaymentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot` (
  `PilotID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL,
  `LastName` VARCHAR(50) NULL,
  `LicenseNumber` VARCHAR(20) NULL,
  `ExperienceYears` INT NULL,
  `Flight_FlightID` INT NOT NULL,
  `Flight_Airport_AirportID` INT NOT NULL,
  `Flight_Aircraft_AircraftID` INT NOT NULL,
  `Flight_Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`PilotID`, `Flight_FlightID`, `Flight_Airport_AirportID`, `Flight_Aircraft_AircraftID`, `Flight_Airline_AirlineID`),
  INDEX `fk_Pilot_Flight1_idx` (`Flight_FlightID` ASC, `Flight_Airport_AirportID` ASC, `Flight_Aircraft_AircraftID` ASC, `Flight_Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_Pilot_Flight1`
    FOREIGN KEY (`Flight_FlightID` , `Flight_Airport_AirportID` , `Flight_Aircraft_AircraftID` , `Flight_Airline_AirlineID`)
    REFERENCES `mydb`.`Flight` (`FlightID` , `Airport_AirportID` , `Aircraft_AircraftID` , `Airline_AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`CrewMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrewMember` (
  `CrewMemberID` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Role` VARCHAR(45) NULL,
  `ExperienceYears` INT NULL,
  `FlightID` INT NULL,
  `Flight_FlightID` INT NOT NULL,
  `Flight_Airport_AirportID` INT NOT NULL,
  `Flight_Aircraft_AircraftID` INT NOT NULL,
  `Flight_Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`CrewMemberID`, `Flight_FlightID`, `Flight_Airport_AirportID`, `Flight_Aircraft_AircraftID`, `Flight_Airline_AirlineID`),
  INDEX `fk_CrewMember_Flight1_idx` (`Flight_FlightID` ASC, `Flight_Airport_AirportID` ASC, `Flight_Aircraft_AircraftID` ASC, `Flight_Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_CrewMember_Flight1`
    FOREIGN KEY (`Flight_FlightID` , `Flight_Airport_AirportID` , `Flight_Aircraft_AircraftID` , `Flight_Airline_AirlineID`)
    REFERENCES `mydb`.`Flight` (`FlightID` , `Airport_AirportID` , `Aircraft_AircraftID` , `Airline_AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `SeatID` INT NOT NULL,
  `SeatNumber` VARCHAR(10) NULL,
  `Class` VARCHAR(20) NULL,
  `FlightID` INT NULL,
  `Flight_FlightID` INT NOT NULL,
  `Flight_Airport_AirportID` INT NOT NULL,
  `Flight_Aircraft_AircraftID` INT NOT NULL,
  `Flight_Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`SeatID`, `Flight_FlightID`, `Flight_Airport_AirportID`, `Flight_Aircraft_AircraftID`, `Flight_Airline_AirlineID`),
  INDEX `fk_Seat_Flight1_idx` (`Flight_FlightID` ASC, `Flight_Airport_AirportID` ASC, `Flight_Aircraft_AircraftID` ASC, `Flight_Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_Flight1`
    FOREIGN KEY (`Flight_FlightID` , `Flight_Airport_AirportID` , `Flight_Aircraft_AircraftID` , `Flight_Airline_AirlineID`)
    REFERENCES `mydb`.`Flight` (`FlightID` , `Airport_AirportID` , `Aircraft_AircraftID` , `Airline_AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `TicketID` INT NOT NULL,
  `BookingID` INT NULL,
  `SeatID` INT NULL,
  `IssueDate` DATETIME NULL,
  `Price` DECIMAL(10,2) NULL,
  `Booking_BookingID` INT NOT NULL,
  `Booking_User_UserID` INT NOT NULL,
  `Booking_Flight_FlightID` INT NOT NULL,
  `Booking_Payment_PaymentID` INT NOT NULL,
  `Seat_SeatID` INT NOT NULL,
  `Seat_Flight_FlightID` INT NOT NULL,
  `Seat_Flight_Airport_AirportID` INT NOT NULL,
  `Seat_Flight_Aircraft_AircraftID` INT NOT NULL,
  `Seat_Flight_Airline_AirlineID` INT NOT NULL,
  PRIMARY KEY (`TicketID`, `Booking_BookingID`, `Booking_User_UserID`, `Booking_Flight_FlightID`, `Booking_Payment_PaymentID`, `Seat_SeatID`, `Seat_Flight_FlightID`, `Seat_Flight_Airport_AirportID`, `Seat_Flight_Aircraft_AircraftID`, `Seat_Flight_Airline_AirlineID`),
  INDEX `fk_Ticket_Booking1_idx` (`Booking_BookingID` ASC, `Booking_User_UserID` ASC, `Booking_Flight_FlightID` ASC, `Booking_Payment_PaymentID` ASC) VISIBLE,
  INDEX `fk_Ticket_Seat1_idx` (`Seat_SeatID` ASC, `Seat_Flight_FlightID` ASC, `Seat_Flight_Airport_AirportID` ASC, `Seat_Flight_Aircraft_AircraftID` ASC, `Seat_Flight_Airline_AirlineID` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Booking1`
    FOREIGN KEY (`Booking_BookingID` , `Booking_User_UserID` , `Booking_Flight_FlightID` , `Booking_Payment_PaymentID`)
    REFERENCES `mydb`.`Booking` (`BookingID` , `User_UserID` , `Flight_FlightID` , `Payment_PaymentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Seat1`
    FOREIGN KEY (`Seat_SeatID` , `Seat_Flight_FlightID` , `Seat_Flight_Airport_AirportID` , `Seat_Flight_Aircraft_AircraftID` , `Seat_Flight_Airline_AirlineID`)
    REFERENCES `mydb`.`Seat` (`SeatID` , `Flight_FlightID` , `Flight_Airport_AirportID` , `Flight_Aircraft_AircraftID` , `Flight_Airline_AirlineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`LoyaltyProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoyaltyProgram` (
  `LoyaltyProgramID` INT NOT NULL,
  `ProgramName` VARCHAR(50) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`LoyaltyProgramID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`UserLoyalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserLoyalty` (
  `UserLoyaltyID` INT NOT NULL,
  `UserID` INT NULL,
  `LoyaltyProgramID` INT NULL,
  `PointsAccumulated` INT NULL,
  `User_UserID` INT NOT NULL,
  `LoyaltyProgram_LoyaltyProgramID` INT NOT NULL,
  PRIMARY KEY (`UserLoyaltyID`, `User_UserID`, `LoyaltyProgram_LoyaltyProgramID`),
  INDEX `fk_UserLoyalty_User1_idx` (`User_UserID` ASC) VISIBLE,
  INDEX `fk_UserLoyalty_LoyaltyProgram1_idx` (`LoyaltyProgram_LoyaltyProgramID` ASC) VISIBLE,
  CONSTRAINT `fk_UserLoyalty_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserLoyalty_LoyaltyProgram1`
    FOREIGN KEY (`LoyaltyProgram_LoyaltyProgramID`)
    REFERENCES `mydb`.`LoyaltyProgram` (`LoyaltyProgramID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Baggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Baggage` (
  `BaggageID` INT NOT NULL,
  `BookingID` INT NULL,
  `Weight` DECIMAL(5,2) NULL,
  `Type` VARCHAR(20) NULL,
  `Booking_BookingID` INT NOT NULL,
  `Booking_User_UserID` INT NOT NULL,
  `Booking_Flight_FlightID` INT NOT NULL,
  `Booking_Payment_PaymentID` INT NOT NULL,
  PRIMARY KEY (`BaggageID`, `Booking_BookingID`, `Booking_User_UserID`, `Booking_Flight_FlightID`, `Booking_Payment_PaymentID`),
  INDEX `fk_Baggage_Booking1_idx` (`Booking_BookingID` ASC, `Booking_User_UserID` ASC, `Booking_Flight_FlightID` ASC, `Booking_Payment_PaymentID` ASC) VISIBLE,
  CONSTRAINT `fk_Baggage_Booking1`
    FOREIGN KEY (`Booking_BookingID` , `Booking_User_UserID` , `Booking_Flight_FlightID` , `Booking_Payment_PaymentID`)
    REFERENCES `mydb`.`Booking` (`BookingID` , `User_UserID` , `Flight_FlightID` , `Payment_PaymentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `RouteID` INT NOT NULL,
  `OriginAirportID` INT NULL,
  `DestinationAirportID` INT NULL,
  `Distance` INT NULL,
  `Duration` VARCHAR(10) NULL,
  `Airport_AirportID` INT NOT NULL,
  PRIMARY KEY (`RouteID`, `Airport_AirportID`),
  INDEX `fk_Route_Airport1_idx` (`Airport_AirportID` ASC) VISIBLE,
  CONSTRAINT `fk_Route_Airport1`
    FOREIGN KEY (`Airport_AirportID`)
    REFERENCES `mydb`.`Airport` (`AirportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
